import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getFirestore, doc, getDoc, updateDoc, increment } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const appConfig = { apiKey: "AIzaSyD-QrqKxjes9f1TgyJOffiQzSMRncf84L0", authDomain: "cohi-survey-engine.firebaseapp.com", projectId: "cohi-survey-engine" };
const app = !getApps().length ? initializeApp(appConfig) : getApp();
const db = getFirestore(app);

let currentVaultId = null;
let sessionStartTime = null;

// Get ID from URL generated by Dashboard
const urlParams = new URLSearchParams(window.location.search);
const projectId = urlParams.get('id');

window.unlockVault = async () => {
    const pin = document.getElementById('vaultPinInput').value.trim();
    if(!projectId) return alert("Invalid Secure Link. Contact your designer.");
    
    try {
        const docRef = doc(db, "surveys", projectId);
        const vaultDoc = await getDoc(docRef);
        
        if(!vaultDoc.exists()) return alert("Secure document not found.");
        const data = vaultDoc.data();
        
        // Local PIN verification (Safe because only authorized URLs have the ID)
        if(data.customerProfile?.vaultPIN !== pin) {
            return alert("Invalid PIN. Please check your text message.");
        }

        currentVaultId = projectId;
        sessionStartTime = Date.now();
        
        // Log telemetry
        await updateDoc(docRef, { "vaultTelemetry.totalOpens": increment(1), "vaultTelemetry.isUnlocked": true });

        renderVaultContent(data);
    } catch(e) {
        console.error(e);
        alert("Connection error securing the vault.");
    }
};

function renderVaultContent(data) {
    document.getElementById('loginGate').style.display = 'none';
    document.getElementById('vaultContent').style.display = 'block';

    if(document.getElementById('customerGreeting')) document.getElementById('customerGreeting').innerText = `Welcome, ${data.customerProfile?.leadName || 'Customer'}`;
    if(document.getElementById('vaultStatus')) document.getElementById('vaultStatus').innerText = `Stage: ${data.pipelineStatus || 'Reviewing Options'}`;

    // Show 3D Render if available
    const renderContainer = document.getElementById('3dRenderContainer');
    if(renderContainer && data.uDesignBridge?.render3DUrl) {
        renderContainer.innerHTML = `<img src="${data.uDesignBridge.render3DUrl}" style="width:100%; border-radius:8px; border:2px solid #0dcaf0; margin-top:10px;" />`;
    }

    // Show PDF Quote if available
    const quoteContainer = document.getElementById('quoteContainer');
    if(quoteContainer && data.uDesignBridge?.quotePdfUrl) {
        quoteContainer.innerHTML = `<a href="${data.uDesignBridge.quotePdfUrl}" download="Your_Quote.pdf" style="background:#10b981; color:white; padding:15px; border-radius:8px; display:block; text-align:center; text-decoration:none; font-weight:bold; margin-top:15px;">⬇️ Download Official Quote</a>`;
    }
}

// Track Exit Time
window.addEventListener('beforeunload', () => {
    if(currentVaultId && sessionStartTime) {
        const timeSpentMins = Math.round((Date.now() - sessionStartTime) / 60000);
        if(timeSpentMins > 0) {
            navigator.sendBeacon(`https://firestore.googleapis.com/v1/projects/cohi-survey-engine/databases/(default)/documents/surveys/${currentVaultId}?updateMask=vaultTelemetry.timeSpentMinutes`, JSON.stringify({
                fields: { "vaultTelemetry.timeSpentMinutes": { integerValue: timeSpentMins } }
            }));
        }
    }
});
